[project]
name = "aiia"
description = "A suite of powerful, intuitive, and highly customizable nodes for ComfyUI, featuring a high-performance Media Browser and OOM-safe video tools."
version = "1.4.22"
license = {file = "LICENSE"}
readme = "README.md"
authors = [
    { name = "Hawk Lee", email = "l.y@live.cn" }
]
keywords = ["ComfyUI", "Audio", "Video", "CosyVoice", "PersonaLive", "NeMo", "Diarization"]
dependencies = [
    "soundfile",
    "numpy",
    "matplotlib",
    "torchaudio"
]

[project.urls]
Repository = "https://github.com/havvk/ComfyUI_AIIA"
#  Used by Comfy Registry https://registry.comfy.org

[tool.comfy]
PublisherId = "hawk"
DisplayName = "ComfyUI_AIIA"
Icon = "https://github.com/user-attachments/assets/358b9ca9-59c8-4433-b84c-c150503af04a"

